### ISSUE TITLE
dataframe display with blank white stripe

### ISSUE THREAD

**Issue by ixzh** [Pocket-titan/DarkMode#6]
Just display any dataframe when in dark mode, the head row and left-most column are blank white... any solution?
![image](https://user-images.githubusercontent.com/14981695/106427506-86a5f700-6435-11eb-8424-97fc42ac736a.png)

**Comment by vsdsantos** [comment]
maybe we can use a styling like this
```css
/* for the fixed header */
table.pluto-table .schema-names th, table.pluto-table .schema-types th:first-child {
    background-color: background_color;
}

/* for the rows numbers */
table.pluto-table tbody th:first-child {
    background-color: background_color;
}
/* for the hovering header*/
table.pluto-table .schema-types th {
    background-color: background_color;
    color: output_color;
}
```

Here's how it looks like
![image](https://user-images.githubusercontent.com/5622934/106223211-c19ef500-61bf-11eb-85ed-b0222559a2a5.png)

I'm just not sure how to PR this.
